variable "region" {}
variable "records" {}
variable "zone_id" {}
variable "react_zone_name" {}
variable "admin_zone_name" {}
variable "registry_zone_name" {}
variable "rancher_zone_name" {}
variable "kibana_zone_name" {}
variable "jenkins_zone_name" {}
variable "zone_type" {}
variable "zone_ttl"  {}
